from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    """
    Represents the state of the agent workflow.

    Attributes:
        input (str): The initial input query or problem statement.
        experts (List[Dict[str, str]]): A list of recruited experts, where each expert is a dictionary containing details like name, role, bias, and skill.
        hypotheses (List[Dict[str, str]]): A list of hypotheses generated by the experts.
        debate_minutes (str): The minutes or transcript of the debate between experts and the Devil's Advocate.
        final_solution (str): The synthesized final solution.
        confidence_score (float): The confidence score of the solution (0-100).
        iterations (int): The number of iterations the workflow has gone through.
    """
    input: str
    experts: List[Dict[str, str]]  # List of dicts with keys: name, role, bias, skill
    hypotheses: List[Dict[str, str]] # List of dicts with keys: expert_name, hypothesis
    debate_minutes: str
    final_solution: str
    confidence_score: float
    knowledge_gaps: List[str]
    visualization_code: str
    iterations: int
    temperature: float
    target_confidence_score: float
    max_iterations: int
    web_search_enabled: bool
    model_name: str
    language: str
